package com.mcy.infoboom.domain;

public class TestData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_data.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_data.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_data.flag
     *
     * @mbggenerated
     */
    private Byte flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_data.id
     *
     * @return the value of test_data.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_data.id
     *
     * @param id the value for test_data.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_data.name
     *
     * @return the value of test_data.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_data.name
     *
     * @param name the value for test_data.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_data.flag
     *
     * @return the value of test_data.flag
     *
     * @mbggenerated
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_data.flag
     *
     * @param flag the value for test_data.flag
     *
     * @mbggenerated
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}